# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 01:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.TextField()),
                ('inicio', models.DateTimeField()),
                ('fim', models.DateTimeField()),
                ('progresso', models.FloatField()),
                ('linkGithub', models.URLField()),
                ('linkGoogleDrive', models.URLField()),
                ('linkSlack', models.URLField()),
                ('linkTaiga', models.URLField()),
            ],
        ),
    ]
