# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoProjetos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='linkGithub',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='linkGoogleDrive',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='linkSlack',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='linkTaiga',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='projeto',
            name='progresso',
            field=models.FloatField(blank=True),
        ),
    ]
