# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoProjetos', '0002_auto_20160520_0117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='progresso',
            field=models.FloatField(),
        ),
    ]
