# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-20 01:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoProjetos', '0003_auto_20160520_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='fase',
            field=models.CharField(choices=[('I', 'Inception'), ('C', 'Concepção'), ('D', 'Desenvolvimento'), ('M', 'Implantação'), ('T', 'TLE')], default='I', max_length=1),
        ),
        migrations.AddField(
            model_name='projeto',
            name='metodologia',
            field=models.CharField(choices=[('C', 'Cascata'), ('I', 'Iterativo'), ('A', 'Agil'), ('E', 'Evolutivo')], default='C', max_length=1),
        ),
        migrations.AddField(
            model_name='projeto',
            name='prioridade',
            field=models.CharField(choices=[('B', 'Baixa'), ('M', 'Média'), ('A', 'Alta')], default='B', max_length=1),
        ),
        migrations.AddField(
            model_name='projeto',
            name='situacao',
            field=models.CharField(choices=[('P', 'Pendente'), ('E', 'Em andamento'), ('F', 'Finalizado')], default='P', max_length=1),
        ),
    ]
