# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-29 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestaoProjetos', '0004_auto_20160520_0133'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntidadeExterna',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('pessoaContato', models.CharField(max_length=80)),
                ('telefone', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=100)),
            ],
        ),
    ]
